---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/notes/{id}/related":
    get:
      summary: retrieves related notes
      tags:
      - notes
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: include_ancestors
        in: query
        required: false
        schema:
          type: boolean
      - name: include_descendants
        in: query
        required: false
        schema:
          type: boolean
      - name: include_user
        in: query
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/notes_array"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/rfc7807"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/rfc7807"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: api.notes.club
components:
  schemas:
    notes_array:
      description: Array of Notes
      type: array
      items:
        "$ref": "#/components/schemas/note"
    user:
      description: User data
      additionalProperties: false
      properties:
        id:
          description: User id
          type: integer
        name:
          description: Name of the user
          type: string
          nullable: true
        username:
          description: Username
          type: string
        avatar_url:
          description: URL of user's avatar
          type: string
          format: URI
          nullable: true
        created_at:
          description: Creation date and time
          type: string
          format: date-time
        updated_at:
          description: Last modification date and time
          type: string
          format: date-time
      required:
      - id
      - name
      - username
      - created_at
      - updated_at
    note:
      description: Note with user and descendants
      type: object
      allOf:
      - "$ref": "#/components/schemas/note_basic"
      properties:
        descendants:
          "$ref": "#/components/schemas/note_descendants"
        user:
          "$ref": "#/components/schemas/user"
    note_descendants:
      description: Descendants notes of a note
      type: array
      items:
        "$ref": "#/components/schemas/note_basic"
    rfc7807:
      description: Schema for rfc7807 (errors)
      properties:
        type:
          description: A URI reference [RFC3986] that identifies the problem type.
          type: string
          format: uri
        title:
          description: A short, human-readable summary of the problem type.
          type: string
        status:
          description: The HTTP status code ([RFC7231], Section 6) generated by the
            origin server for this occurrence of the problem.
          type: number
        instance:
          description: A URI reference that identifies the specific occurrence of
            the problem.
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of
            the problem.
          type: string
      required:
      - type
    note_basic:
      description: Basic Note data
      properties:
        id:
          description: Note id
          type: integer
        content:
          description: Note content
          type: string
          nullable: true
        user_id:
          description: Id of the note's user
          type: integer
          nullable: true
        ancestry:
          description: 'Id of the note''s parents separated by ''/''. For example:
            ''46/51/52/53'' where 53 would be the parent, 52 the grandparent, etc.'
          type: string
          nullable: true
        created_at:
          description: Creation date and time
          type: string
          format: date-time
        updated_at:
          description: Last modification date and time
          type: string
          format: date-time
        slug:
          description: Slug of the note
          type: string
        position:
          description: Note's position respect to its siblings, if any. Starts at
            1. For root notes its value is 1
          type: integer
          nullable: true
      required:
      - id
      - content
      - user_id
      - ancestry
      - created_at
      - updated_at
      - slug
      - position
