---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/banana":
    get:
      summary: retrieves bananas
      tags:
      - banana
      responses:
        '200':
          description: banana found
          content: {}
  "/v1/notes/{id}/related":
    get:
      summary: retrieves related notes
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '404':
          description: Note not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/rfc7807"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  schemas:
    rfc7807:
      description: Schema for rfc7807 (errors)
      properties:
        type:
          description: A URI reference [RFC3986] that identifies the problem type.
          type: string
          format: uri
        title:
          description: A short, human-readable summary of the problem type.
          type: string
        status:
          description: The HTTP status code ([RFC7231], Section 6) generated by the
            origin server for this occurrence of the problem.
          type: number
        instance:
          description: A URI reference that identifies the specific occurrence of
            the problem.
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of
            the problem.
          type: string
      required:
      - type
    base_note:
      description: Basic Note data
      properties:
        id:
          description: Note id
          type: integer
        content:
          description: Note content
          type: string
          nullable: true
        user_id:
          description: Id of the note's user
          type: integer
          nullable: true
        ancestry:
          description: Id of the note's parent
          type: integer
          nullable: true
        created_at:
          description: Creation date and time
          type: string
        updated_at:
          description: Last modification date and time
          type: string
        slug:
          description: Slug of the note
          type: string
        position:
          description: Note's position respect to its siblings, if any. Starts at
            1. For root notes its value is 1
          type: integer
          nullable: true
      required:
      - id
      - content
      - user_id
      - ancestry
      - created_at
      - updated_at
      - slug
      - position
