---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/banana":
    get:
      summary: retrieves bananas
      tags:
      - focus
      responses:
        '200':
          description: banana found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/note"
            application/xml:
              schema:
                "$ref": "#/components/schemas/note"
  "/v1/notes/{id}/related":
    get:
      summary: retrieves related notes
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '404':
          description: Note not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/rfc7807"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  schemas:
    note_basic:
      description: Basic Note data
      properties:
        id:
          description: Note id
          type: string
        content:
          description: Note content
          type: string
          nullable: true
        user_id:
          description: Id of the note's user
          type: string
          nullable: true
        ancestry:
          description: Id of the note's parent
          type: string
          nullable: true
        created_at:
          description: Creation date and time
          type: date-time
        updated_at:
          description: Last modification date and time
          type: date-time
        slug:
          description: Slug of the note
          type: string
        position:
          description: Note's position respect to its siblings, if any. Starts at
            1. For root notes its value is 1
          type: integer
          nullable: true
      required:
      - id
      - content
      - user_id
      - ancestry
      - created_at
      - updated_at
      - slug
      - position
    note_descendants:
      description: Descendants notes of a note
      additionalProperties: false
      type: array
      items:
        "$ref": "#/components/schemas/note_basic"
    note:
      description: Note with user and descendants
      type: object
      allOf:
      - "$ref": "#/components/schemas/note_basic"
      - "$ref": "#/components/schemas/note_descendants"
