---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/banana":
    get:
      summary: retrieves bananas
      tags:
      - banana
      responses:
        '200':
          description: banana found
          content: {}
  "/v1/notes/{id}/related":
    get:
      summary: retrieves related notes
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '404':
          description: ":not_found"
          content: {}
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  schemas:
    rfc7807:
      description: schema for rfc7807
      properties:
        type:
          description: A URI reference [RFC3986] that identifies the problem type.
          type: string
          format: uri
        title:
          description: A short, human-readable summary of the problem type.
          type: string
        status:
          description: The HTTP status code ([RFC7231], Section 6) generated by the
            origin server for this occurrence of the problem.
          type: number
        instance:
          description: A URI reference that identifies the specific occurrence of
            the problem.
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of
            the problem.
          type: string
      required:
      - type
