---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/banana":
    get:
      summary: retrieves bananas
      tags:
      - banana
      responses:
        '200':
          description: banana found
          content: {}
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
