# frozen_string_literal: true

require "rails_helper"

def add_schema(item, document, schema)
  item[document][:components][:schemas] = item[document][:components][:schemas].merge(schema)
end

RSpec.configure do |config|
  # Specify a root folder where Swagger JSON files are generated
  # NOTE: If you're using the rswag-api to serve API descriptions, you'll need
  # to ensure that it's configured to serve Swagger from the same folder
  # config.swagger_root = Rails.root.join("swagger").to_s
  config.swagger_root = Rails.root.join("docs", "API").to_s

  # Define one or more Swagger documents and provide global metadata for each one
  # When you run the 'rswag:specs:swaggerize' rake task, the complete Swagger will
  # be generated at the provided relative path under swagger_root
  # By default, the operations defined in spec files are added to the first
  # document below. You can override this behavior by adding a swagger_doc tag to the
  # the root example_group in your specs, e.g. describe '...', swagger_doc: 'v2/swagger.json'
  config.swagger_docs = {
    "v1/notes.yaml" => {
      openapi: "3.0.1",
      info: {
        title: "API V1",
        version: "v1"
      },
      paths: {},
      servers: [
        {
          url: "https://{defaultHost}",
          variables: {
            defaultHost: {
              default: "www.example.com"
            }
          }
        }
      ], # servers
      components: {
        schemas: {
          # This key must exist
        }
      } # components
    } # v1/notes.yaml
  } # swagger_docs

  rfc7807_schema = {
    rfc7807: {
      description: "schema for rfc7807",
      properties: {

        type: {
          description: "A URI reference [RFC3986] that identifies the problem type.",
          type: "string",
          format: "uri"
        },
        title: {
          description: "A short, human-readable summary of the problem type.",
          type: "string"
        },
        status: {
          description: "The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.",
          type: "number"
        },
        instance: {
          description: "A URI reference that identifies the specific occurrence of the problem.",
          type: "string"
        },
        detail: {
          description: "A human-readable explanation specific to this occurrence of the problem.",
          type: "string"
        }
      },
      required: %w[type]
    }
  }

  # We could define and schemas directory and automatize this when we have more schemas
  add_schema config.swagger_docs, "v1/notes.yaml", rfc7807_schema

  # Specify the format of the output Swagger file when running 'rswag:specs:swaggerize'.
  # The swagger_docs configuration option has the filename including format in
  # the key, this may want to be changed to avoid putting yaml in json files.
  # Defaults to json. Accepts ':json' and ':yaml'.
  config.swagger_format = :yaml
end
